name: CI Build - WWI-API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    #Operations TO-DO: Add manual trigger
jobs:
  build:
    runs-on: ubuntu-latest
  #Operations TO-DO: Replace or update steps to successfully trigger the workflow
    steps:
    - name: Checkout code


    - name: Setup .NET


    - name: Restore dependencies


    - name: Build solution


    - name: Check code formatting


    - name: Publish build output
